### ISSUE TITLE
Struggling to get to work

### ISSUE THREAD

**Issue by ikolsteren** [angryziber/synology-cast-photos#3]
I cant seem to get to work.   I feel i have all setup correct and even made new folders with full access permissions.
I commented out the lines for the auth token but basically when i am on the sender page no folders show up.
Not sure if there is a more detailed guide to get to work maybe including the php-access-token

**Comment by ikolsteren** [comment]
Did a php test:

open_basedir | /tmp:/var/services/tmp:/var/services/web:/var/services/homes:/volume1/web:/volume1/videos:/volume1/SharedPhotos:/volume1/publish

And from my /web/backend/config

$photos_list_dir = "/volume1/publish"

**Comment by angryziber** [comment]
README improved
