### ISSUE TITLE
Error 404 when casting to TV

### ISSUE THREAD

**Issue by rainy2004** [angryziber/synology-cast-photos#4]
Hi, thank you very much for this great code!

When I try 'receiver' all works fine: I can choose folder with Esc and script shows all photos well.

But when I try to use sender - it doesn't work. I also can choose folder, then start casting to Android TV, there is a black screen, then for a second appears message 'rnd: my_chosen_folder_name', and then Error 404, and that is all.

Do you have any idea what I do wrong? How to solve the problem?

Thanks a lot!

**Comment by angryziber** [comment]
Please register your Chromecast for development on Google Console and then you can use chrome://inspect to see what's happening inside.

Most likely the receiver is not switching to your own receiver's url from the default one hosted at GitHub. For this to work, your own hosted sender must send the url to switch to and you will see this url on the TV screen before you start sending.

**Comment by rainy2004** [comment]
Thanks a lot for your answer! I am investigate this case.
